### PR TITLE
 Add methods to start windows and WSL docker. Edit the wording and formats

### PR DESCRIPTION
**Pull request by ZZhangchen**

### CODE REVIEW

**Comment by ZZhangchen** [comment]
I can see I still failed to combine the two commits into one.

**Comment by junaruga** [comment]
> I can see I still failed to combine the two commits into one.

@ZZhangchen are you trying to do it by `git rebase -i <commit hash>` right?
Which command are you using to "combine the two commits into one"?

**Comment by ZZhangchen** [comment]
I tried again. I think this time should be right.

**Comment by junaruga** [comment]
Yeah perfect!

**Comment by junaruga** [comment]
Now you can type below commands, then you can see your commit that was merged to origin (`team-gogut/yamp-arm`) repository's master branch, on your local repository's master branch.

```
$ git checkout master
```

Now you are on master branch.
Below command pulls commits from original repository's master branch to your local repository's master branch.

```
$ git pull
```

```
$ git log
```

**Comment by ZZhangchen** [comment]
I did it! Thank you for the help along the way, Jun! :)

**Pull request merged**
